extends Node

const b0 = "res://sprites/bit0.png"
const b1 = "res://sprites/bit1.png"
const gateEmpty = "res://sprites/gateEmpty.png"
const gateX = "res://sprites/gateX.png"
const gateY = "res://sprites/gateY.png"
const gateZ = "res://sprites/gateZ.png"
const gateS = "res://sprites/gateS.png"
const gateH = "res://sprites/gateH.png"
const gateCtrl = "res://sprites/gateCtrl.png"
const gateCXt = "res://sprites/gateCXtop.png"
const gateCXb = "res://sprites/gateCXbot.png"

const texts = {
	0 : [
		"This is a quantum circuit", "\n\n",
		"On the left, it shows the input state of the qubit (quantum bit)", "\n",
		"\n[i]|0⟩[/i]\n\n",
		"When you press the [b]evaluate[/b] button, ",
		"the output of the circuit will appear\n\n",
		"Output like",
		"\n\n[i]|0⟩[/i] : 100%\n[i]|1⟩[/i]  :   0%\n\n",
		"means that the output of your circuit is the state [i]|0⟩[/i]",
	],
	1 : [
		"[b]Pauli-X (NOT) Gate[/b]\n\n",
		"flip the state of a qubit\n\n",
		"[b][i]|0⟩[/i][/b] ", gateEmpty, gateX, gateEmpty, " [b][i]|1⟩[/i][/b]", "\n",
		"[b][i]|1⟩[/i][/b] ", gateEmpty, gateX, gateEmpty, " [b][i]|0⟩[/i][/b]", "\n",
		"[code]*[input] -[gate]- [output][/code]\n\n",
		"Just like a classical bit, a qubit can be in the state of ", 
		"[i]|0⟩[/i] and [i]|1⟩[/i]", "\n\n",
		"You can manipulate the state of the qubits by using quantum logic gates", "\n\n",
		"For example, this is Pauli-X gate (NOT gate)", "\n\n",
		"res://sprites/gateX.png", "\n\n",
		"Pauli-X gate (just like a NOT gate in classical logic gates) ",
		"will flip a qubit from state [i]|0⟩[/i] into state [i]|1⟩[/i] and vice versa.",
	],
	2 : [
		"A system can consist of multiple qubits. ",
		"The state of each qubit is not represented individually, ",
		"but rather, as a single system. \n\n",
		"For example, in a two-qubit system, the state [i]|10⟩[/i] ",
		"means that the first qubit is in the state [i]|0⟩[/i], and ",
		"the second qubit is in the state [i]|1⟩[/i].",
	],
	3 : [],
	4 : [
		"[b]Control node[/b]\n\n",
		"turn on or off a gate based on the state of the control qubits\n",
		"Example, CNOT (Controlled Not) :\n\n",
		"[b][i]|0⟩[/i][/b] ", gateEmpty, gateCXt, gateEmpty, " [b][i]|0⟩[/i][/b]", "\n",
		"[b][i]|0⟩[/i][/b] ", gateEmpty, gateCXb, gateEmpty, " [b][i]|0⟩[/i][/b]", "\n\n",
		"[b][i]|1⟩[/i][/b] ", gateEmpty, gateCXt, gateEmpty, " [b][i]|1⟩[/i][/b]", "\n",
		"[b][i]|0⟩[/i][/b] ", gateEmpty, gateCXb, gateEmpty, " [b][i]|1⟩[/i][/b]", "\n\n",
		"the X gate is only active and flips the bottom qubit, if the top qubit ",
		"(control qubit) is [i]|1⟩[/i]\n\n",
		"To control the flow of your quantum algorithm, you can use control nodes. ",
		"If a control node is paired with a gate, that gate will be active only if ",
		"the control qubit is in the state [i]|1⟩[/i]",
	],
	5 : [],
	6 : [],
	7 : [
		"[b]Hadamard gate[/b]\n\n",
		"can turn a qubit from a basis state into a superposition\n\n",
		"[b][i]|0⟩[/i][/b] ", gateEmpty, gateH, gateEmpty, 
		" [b][i]|0⟩ + |1⟩[/i][/b]", "\n",
		"[b][i]|1⟩[/i][/b] ", gateEmpty, gateH, gateEmpty, 
		" [b][i]|0⟩ – |1⟩[/i][/b]", "\n",
		"[code]*not normalized[/code]\n",
		"\n",
		"The cool thing about a quantum system is [b]superposition[/b]. ",
		"A qubit can be in a state called a [b]superposition[/b].\n\n",
		"[i]|0⟩[/i] and [i]|1⟩[/i] are called the basis states, ",
		"and a qubit can be in a superposition of those two states, ",
		"which mean, when the qubit is measured, ",
		"it has some probability to be measured as [i]|0⟩[/i] or [i]|1⟩[/i]",
		". Or what some people would say as being in multiple states at once",
		"\n\n",
		"A fun interpretation of this phenomenon is that ",
		"a hadamard gate can split the universe into two versions. ",
		"One in which the qubit is in the state [i]|0⟩[/i], ",
		"and one in which the qubit is in the state [i]|1⟩[/i]",
		"[img=500]res://img/hadamard-split.png[/img]",
	],
	8 : [],
	9 : [],
	10 : [],
	11 : [
		"Entanglement is when two or more quantum system have properties that are linked.\n\n",
		"For example, two qubits can be entangled so that when measured, both qubits will always be in the same state. ",
		"As in the [i]|00⟩ + |11⟩[/i] state, if the first qubit is measured as [i]|0⟩[/i], ",
		"then the only possible state of the system is [i]|00⟩[/i], meaning that the second qubit must also be [i]|0⟩[/i].\n\n",
		"You can contrast that with the state [i]|00⟩ + |01⟩ + |10⟩ + |11⟩[/i] where both qubits are independent. ",
		"Knowing the state of one doesn't tell the state of the other",
	],
	12 : [],
	13 : [
		"The coefficient of the state carries information about something called [b]phase[/b]. ",
		"For example, both [i]|1⟩[/i] and [i]-|1⟩[/i] mean the state [i]|1⟩[/i], ",
		"but with opposite phase.\n\n",
		"Recall that when you apply the hadamard gate to the basis state, it's\n\n",
		"[b][i]|0⟩[/i][/b] ", gateEmpty, gateH, gateEmpty, 
		" [b][i]|0⟩ + |1⟩[/i][/b]", "\n",
		"[b][i]|1⟩[/i][/b] ", gateEmpty, gateH, gateEmpty, 
		" [b][i]|0⟩ – |1⟩[/i][/b]", "\n",
		"[code]*not normalized[/code]\n\n",
		"Both the state [i]|0⟩ + |1⟩[/i] and [i]|0⟩ – |1⟩[/i] ",
		"are superpositions of the basis states [i]|0⟩[/i] and [i]|1⟩[/i]. ",
		"And when measured, both will output [i]|0⟩[/i] 50% of the time, ",
		"and [i]|1⟩[/i] 50% of the time.\n\n",
		"This phase of the basis states carry extra information about the qubit. ",
		"You can see that when applying two [b]Hadamard[/b] gates right after the other,",
		"some states will destructively interfere and the qubit will return to it's original state.\n\n",
		"[b][i]|0⟩[/i][/b] ", gateEmpty, gateH, 
		" [b][i]|0⟩ + |1⟩[/i][/b]", gateH, gateEmpty,
		" [b][i]|0⟩[/i][/b]",
		"\n",
		"[i]H|0⟩ → |0⟩ + |1⟩[/i]\n",
		"[i]H(|0⟩+|1⟩) = H|0⟩ + H|1⟩ → |0⟩ + |1⟩ + |0⟩ - |1⟩ = 2|0⟩[/i]\n\n",
		"[b][i]|1⟩[/i][/b] ", gateEmpty, gateH, 
		" [b][i]|0⟩ - |1⟩[/i][/b]", gateH, gateEmpty,
		" [b][i]|1⟩[/i][/b]",
		"\n",
		"[i]H|1⟩ → |0⟩ – |1⟩[/i]\n",
		"[i]H(|0⟩-|1⟩) = H|0⟩ – H|1⟩ → |0⟩ + |1⟩ – (|0⟩ – |1⟩) = 2|1⟩[/i]\n\n\n",
		"[code]*why the result here is [i]2|⋅⟩[/i] and not just [i]|⋅⟩[/i] will be explained in the next level[/code]"
	],
	14 : [
		"The coefficient also carries information about the probability of measuring certain states.\n\n",
		"Previously, we used non-normalized notation as in [i]|0⟩ + |1⟩[/i]. ",
		"Here, the probability can still be seen by looking at the ratio of the coefficients. ",
		"In the non-normalized state [i]4|0⟩ + 2|1⟩[/i], the probability of measuring [i]|0⟩[/i] ",
		"is greater than measuring [i]|1⟩[/i].\n\n",
		"The probability of measuring a certain state is easier to see in the normalized state notation.\n\n",
		"For the state [i]|ψ⟩ = α|0⟩ + β|1⟩[/i],\n",
		"the probability of measuring [i]|0⟩[/i] is [i]|α|[/i]², and\n",
		"the probability of measuring [i]|1⟩[/i] is [i]|β|[/i]².\n\n",
		"both [i]α[/i] and [i]β[/i] can be a complex numbers.",
		"\n\n",
		"The normalized hadamard gate is\n\n",
		"[b][i]|0⟩[/i][/b] ", gateEmpty, gateH, gateEmpty, 
		" [b][i](|0⟩ + |1⟩)/sqrt(2)[/i][/b]", "\n",
		"[b][i]|1⟩[/i][/b] ", gateEmpty, gateH, gateEmpty, 
		" [b][i](|0⟩ – |1⟩)/sqrt(2)[/i][/b]", "\n",
		"You can see that after applying one hadamard gate, the resulting state has ",
		"basis state coefficients of [i]1/sqrt(2)[/i], meaning that the probability of measuring ",
		"each basis state is [i][1/sqrt(2)][/i]²[i] = 1/2 = 50%[/i].\n\n",
		"Using this, we can try calculating the effect of two Hadamard gate\n\n",
		"[i]H(H|0⟩)[/i]\n",
		"[i]= H(|0⟩/sqrt(2) + |1⟩/sqrt(2))[/i]\n",
		"[i]= H|0⟩/sqrt(2) + H|1⟩/sqrt(2)[/i]\n",
		"[i]= (|0⟩/sqrt(2) + |1⟩/sqrt(2))/sqrt(2) + (|0⟩/sqrt(2) – |1⟩/sqrt(2))/sqrt(2)[/i]\n",
		"[i]= (|0⟩ + |1⟩)/2 + (|0⟩ – |1⟩)/2[/i]\n",
		"[i]= |0⟩/2 + |1⟩/2 + |0⟩/2 – |1⟩/2[/i]\n",
		"[i]= |0⟩[/i]",
	],
	15 : [],
	16 : [
		"[b]Pauli-Z Gate[/b]\n\n",
		"flip the phase of [i]|1⟩[/i] state, [i]|0⟩[/i] is unaffected\n\n",
		"[b][i]|0⟩[/i][/b] ", gateEmpty, gateZ, gateEmpty, " [b][i]|0⟩[/i][/b]", "\n",
		"[b][i]|1⟩[/i][/b] ", gateEmpty, gateZ, gateEmpty, " [b][i]–|1⟩[/i][/b]", "\n\n",
		"for a superposition state\n\n",
		"[b][i]α|0⟩ + β|1⟩[/i][/b] ", gateEmpty, gateZ, gateEmpty, 
		" [b][i]α|0⟩ + (–β)|1⟩[/i][/b]", "\n",
	],
	17 : [],
	18 : [
		"[b]Pauli-Y Gate[/b]\n\n",
		"Reverse and turn the phase of [i]|0⟩[/i] and [i]|1⟩[/i] by [i]±π/2[/i]\n\n",
		"[b][i]|0⟩[/i][/b] ", gateEmpty, gateY, gateEmpty, " [b][i]i|1⟩[/i][/b]", "\n",
		"[b][i]|1⟩[/i][/b] ", gateEmpty, gateY, gateEmpty, " [b][i]–i|0⟩[/i][/b]", "\n\n",
		"for a superposition state\n\n",
		"[b][i]α|0⟩ + β|1⟩[/i][/b] ", gateEmpty, gateY, gateEmpty, 
		" [b][i]–βi|0⟩ + αi|1⟩[/i][/b]", "\n",
	],
	19 : [
		"[b]Phase Gate[/b]\n\n",
		"Turn the phase of [i]|1⟩[/i] and by [i]π/2[/i] (multiplication by [i]i[/i])\n\n",
		"[b][i]|0⟩[/i][/b] ", gateEmpty, gateS, gateEmpty, " [b][i]|0⟩[/i][/b]", "\n",
		"[b][i]|1⟩[/i][/b] ", gateEmpty, gateS, gateEmpty, " [b][i]i|1⟩[/i][/b]", "\n\n",
		"for a superposition state\n\n",
		"[b][i]α|0⟩ + β|1⟩[/i][/b] ", gateEmpty, gateS, gateEmpty, 
		" [b][i]α|0⟩ + βi|1⟩[/i][/b]", "\n",
	],
	20 : [],
	21 : [],
	22 : [],
	23 : [],
	24 : [],
	25 : [],
	26 : [],
	27 : [],
	28 : [],
	29 : [],
	30 : [],
	31 : [],
	32 : [],
	33 : [],
	34 : [],
	35 : [],
	36 : [],
	37 : [],
	38 : [],
	39 : [],
	40 : [],
	41 : [],
	42 : [],
	43 : [],
	44 : [],
	45 : [],
	46 : [],
	47 : [],
	48 : [],
	49 : [],
	50 : [],
	51 : [],
	52 : [],
	53 : [],
	54 : [],
	55 : [],
	56 : [],
	57 : [],
	58 : [],
	59 : [],
	60 : [],
	61 : [],
	62 : [],
	63 : [],
	64 : [],
	65 : [],
	66 : [],
	67 : [],
	68 : [],
	69 : [],
	70 : [],
	101 : [],
	102 : [],
	103 : [],
	104 : [],
}
